# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('files', models.FileField(upload_to='./files', verbose_name='\u6587\u4ef6')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('psw', models.CharField(max_length=16)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('qq', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsapp.Users'),
        ),
        migrations.AddField(
            model_name='contents',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsapp.Users'),
        ),
    ]
