# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptwo',
            name='timestamp',
            field=models.CharField(default=b'2018-05-02 11:38:46', max_length=20),
        ),
    ]
