# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsapp', '0003_auto_20180503_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pthree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('files', models.FileField(upload_to='./upload', verbose_name='\u6587\u4ef6')),
            ],
        ),
        migrations.AlterField(
            model_name='ptwo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
